DROP INDEX IF EXISTS IX_StockAsset_Ticker;
DROP INDEX IF EXISTS IX_CryptoAsset_Ticker;
DROP INDEX IF EXISTS IX_AssetPrice_AssetID_Date;

DROP TABLE IF EXISTS StockAsset;
DROP TABLE IF EXISTS CryptoAsset;
DROP TABLE IF EXISTS Asset;
DROP TABLE IF EXISTS AssetPrice;